version: '3'

volumes:
  db-store:

services:
  pm-php:
    container_name: pm-php
    build: ./docker/laravel
    volumes:
      - ./src:/var/www
    environment:
      TZ: Asia/Tokyo
    env_file:
      - ./src/.env
    restart: always

  pm-nginx:
    image: nginx
    container_name: pm-nginx
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - pm-php

  pm-mysql:
    image: mysql:8.0.20
    platform: linux/amd64
    container_name: pm-mysql
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306